import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from '../components/Footer'; 
import Header from '../components/Header'; 
import Hero from '../components/Hero';
import Gtext from '../components/Gtext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "5-template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Hero /> {/* Hero component */}
        <Header /> {/* Header component */}
        {children} {/* Page content */}
        <Gtext />
        <Footer /> {/* Footer component */}
      </body>
    </html>
  );
}
